version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Pass the API key to the container.
      # Make sure GEMINI_API_KEY is set in your local environment or a .env file.
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      # Mount the cache directory to persist the daily quiz across container restarts
      - ./.cache:/app/.cache
      - .env:/app/.env
    restart: always
